# Generated by Django 4.2.27 on 2025-12-23 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioitem",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="portfolioitem",
            name="project_url",
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="portfolio/archives/",
                verbose_name="Архив проекта",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="author_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_testimonials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(upload_to="portfolio/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец визитки",
            ),
        ),
    ]
