# Generated by Django 4.2.27 on 2025-12-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_remove_portfolioitem_github_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Должность"
            ),
        ),
    ]
