# Generated by Django 4.2.27 on 2025-12-23 22:20

from django.db import migrations, models


def set_date_from_created_at(apps, schema_editor):
    """Устанавливает дату проекта из created_at для существующих записей"""
    PortfolioItem = apps.get_model('cards', 'PortfolioItem')
    for item in PortfolioItem.objects.filter(date__isnull=True):
        item.date = item.created_at.date()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_customuser_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Проект портфолио",
                "verbose_name_plural": "Проекты портфолио",
            },
        ),
        migrations.RemoveField(
            model_name="portfolioitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="date",
            field=models.DateField(default="2024-01-01", verbose_name="Дата проекта"),
        ),
        migrations.RunPython(set_date_from_created_at),
        migrations.AlterField(
            model_name="portfolioitem",
            name="date",
            field=models.DateField(verbose_name="Дата проекта"),
        ),
    ]
